# Занятие 1
# Прикладная алгебра и численные методы
# Матрицы и системы линейных алгебраических уравнений (СЛАУ)
# Псевдообратная матрица
Для решения задач линейной алгебры будут использоваться написанные на Python математические библиотеки numpy и scipy:

numpy:
https://numpy.org/doc/stable/reference/routines.linalg.html

scipy:
https://docs.scipy.org/doc/scipy/reference/linalg.html

Сначала познакомимся с возможностями работы с матрицами в numpy.

## Подключение модуля numpy.
Для того, чтобы пользоваться функциями и классами из numpy, нужно "подключить" эту библиотеку, это делается через импорт. Сложилась страдиция сокращать название numpy до np и в вызовах функций явно указывать сокращенное название пакета, чтобы избежать путаницы при вызовах в однй программе одноименных функций из разных пакетов. Мы будем следовать этим неписанным правилам.

In [2]:
import numpy as np

После запуска ячейки с импортом из любой кодовой ячейки доступны все функции пакета numpy, но для их вызова нужно перед именем функции писать np.

В файлах Jupyter Notebook (.ipynb) единое пространство имен, поэтому из любой кодовой ячейки "видны" все переменные и функции всех запущенных хотя бы один ячеек. Пока код в ячейке не запущен, никакой информации в пространство имен не попадает.
## Реализация матриц в numpy, действия с матрицами
### Создание матриц
В numpy в роли матриц могут использоваться списки list, например, так можно перемножать матрицы с помощью dot

In [3]:
a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]
print(a, b, np.dot(a, b), sep='\n\n')

[[1, 2], [3, 4]]

[[5, 6], [7, 8]]

[[19 22]
 [43 50]]


Заметим, что dot возвращает не список, а array.

Для сложения матриц списки не годятся, при сложении списков получается добавление второго слагаемого в "хвост" первому:

In [4]:
a + b

[[1, 2], [3, 4], [5, 6], [7, 8]]

Для представления матриц будем в соответствии с рекомендациями разработчиков numpy пользоваться такой структурой данных как array. Запишем в переменные a_np и b_np данные в виде array, построенных на основе вложенных списков  a и b, а затем используем a_np и b_np при сложении и вычитании матриц:

In [5]:
a_np = np.array(a)
b_np = np.array(b)
print(a_np + b_np, a_np - b_np, sep='\n\n')

[[ 6  8]
 [10 12]]

[[-4 -4]
 [-4 -4]]


На основе списка можно сделать и матрицу matrix, на пример, с помощью mat

In [6]:
np.mat(a)

matrix([[1, 2],
        [3, 4]])

В последней версии numpy не рекомендуется использовать матрицы matrix, поскольку от них в будущем планируется избавиться, вместо них рекомендуется использовать array.

## Транспонирование
Для транспонирования матрицы используется np.transpose(x)

In [7]:
print(np.transpose(a), np.transpose(a_np), sep='\n\n')

[[1 3]
 [2 4]]

[[1 3]
 [2 4]]


Функция np.transpose возвращает array и в случае, если в качестве аргумента передан array, и если аргумент - list. 

Однако такой код выглядит слишком длинным и неудобочитаемым, поэтому будем пользоваться сокращенной формой, применимой только к array, не к list:

In [8]:
print(a_np.T)

[[1 3]
 [2 4]]


## Функции в Python
Для более наглядного и удобного решения задачи былает удобно разбить ее на подзадачи и каждую подзадачу оформить в виде функции. Функции бывают встроенные, такие как $\sin$ и $\log$, их можно использовать, подключив соответствующий модуль. Можно написать собственные функции следующим образом:
```
def function_name(arg1, ..., arg2=Value):

    .....
    
    return something
```
Ключевое слово return можно опустить, тогда функция вернет в качестве результата None.

У функции могут быть только обязательные аргументы, но могут быть и аргументы со значениями по умолчанию (необязательные аргументы).
Вначале опишем функцию $f$ с обязательными аргументами $x$ и $a$.

При вызове функции аргументы передаются по порядку, в нашем случае сначала значение  $x$, потом $a$.

### Пример 1
Опишем функцию $func\_power(x, a) = x^a$:    

In [9]:
def func_power(x, a):
    return x ** a

При вызове функции сначала передаем значение  $x$, потом $a$. 

In [10]:
func_power(2, 3)

8

### Необязательные аргументы функции
Необязательные аргументы или аргументы со значением по умолчанию передаются всегда ПОСЛЕ обязательных аргументов!!!
### Пример 2
Опишем функцию $g(A, n) = A^n$ с параметром $n$, по умолчанию равным 1. Для умножения матриц можно использовать функцию matmul или использовать вызывающий ее оператор @.

In [11]:
def g(A, n=1):
    if n == 1:
        return A
    res = A
    for i in range(n - 1):
        res = res @ A
    return res

При вызове функции передадим только обязательный аргумент, если нас устраивает значение по умолчанию

In [12]:
A = np.array([[1, 2], [3, 4]])
print(A, g(A), sep='\n\n')

[[1 2]
 [3 4]]

[[1 2]
 [3 4]]


Возведем матрицу в степень 3:

In [13]:
print(A, g(A, 3), sep='\n\n')

[[1 2]
 [3 4]]

[[ 37  54]
 [ 81 118]]


## Аргументы функции, число которых заранее неизвестно
### Пример 3
Перепишем функцию $g$ Примера 2 так, чтобы с ее помощью можно было находить произведение произвольного числа матриц:

In [14]:
def mat_product(*args):
    n = len(args)
    if  n == 0:
        return None
    if n == 1:
        return args[0]
    res = args[0]
    for k in range(1, n):
        res = res @ args[k]
    return res

In [15]:
print(mat_product(A))

[[1 2]
 [3 4]]


In [16]:
B = np.array([[-1, 5], [0, 7]])
C = np.array([[1, 8], [-3, 2]])
print(mat_product(A, B, A))

[[ 56  74]
 [126 166]]


### Пример 4.
Решим СЛАУ
$$
\left\{
\begin{matrix}
2x + 3y - z = 5\\
3x - 2y + z = 2\\
x + y - z = 0
\end{matrix}
\right.
$$
Для решения СЛАУ воспользуемся linalg.solve, аргументы - матрица левой части и столбец правой.

Для проверки правильности решения используем allclose

In [17]:
a = np.array([[2, 3, -1], [3, -2, 1], [1, 1, -1]])
b = np.array([5, 2, 0])
x = np.linalg.solve(a, b)
print(x, a @ x, b, a @ x == b, np.allclose(a @ x, b), sep=', ')

[1. 2. 3.], [5.0000000e+00 2.0000000e+00 4.4408921e-16], [5 2 0], [ True  True False], True


## Псевдообратная матрица
В numpy псевдообратная матрица находится с помощью np.linalg.pinv
## Пример 5
Найти псевдообратную матрицу к матрице
$$
\left(
\begin{matrix}
1 & 2 & 3\\
4 & 5 & 6
\end{matrix}
\right)
$$
Чтобы не воодить вручную каждый элемент матрицы, создадим последовательность натуральных чисел от 1 до 7 и расположим ее элементы в две строки по 3 столбца в каждой. К полученной матрице в форме np.array применим метод pinv().


In [18]:
A = np.arange(1, 7).reshape((2, 3))
A_pinv = np.linalg.pinv(A)
print(A, A_pinv,
      np.allclose(A, A @ (A_pinv @ A)),
      np.allclose(A_pinv, A_pinv @ (A @ A_pinv)), sep='\n\n')

[[1 2 3]
 [4 5 6]]

[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]

True

True


## В scipy тоже есть модуль linalg, 
в нем есть pinv:

In [19]:
import scipy.linalg

In [20]:
A = np.arange(1, 7).reshape((2, 3))
A_pinv = scipy.linalg.pinv(A)
print(A, A_pinv,
      np.allclose(A, A @ (A_pinv @ A)),
      np.allclose(A_pinv, A_pinv @ (A @ A_pinv)), sep='\n\n')

[[1 2 3]
 [4 5 6]]

[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]

True

True


## В пакете символьной математики sympy 
тоже есть псевдообратная матрица:

In [21]:
import sympy

In [22]:
As = sympy.Matrix(A)
As_pinv = As.pinv()
display(As_pinv, As_pinv.evalf(8))

Matrix([
[-17/18,  4/9],
[  -1/9,  1/9],
[ 13/18, -2/9]])

Matrix([
[-0.94444444,  0.44444444],
[-0.11111111,  0.11111111],
[ 0.72222222, -0.22222222]])

## Скелетное разложение
## Пример 6
Построим скелетное разложение для матрицы 
$$
\left(
\begin{matrix}
2 & 3 & -1 & 4\\
-1 & 4 & 1 & 4\\
1 & 7 & 0 & 8
\end{matrix}
\right)
$$
$B$ матрица полного столбцового ранга, $C$-строчного,
тогда псевдообратная матрица находится по формуле
$$
A^+ = C^T(C\cdot C^T)^{-1}(B^T\cdot B)^{-1}B^T
$$

In [23]:
A = sympy.Matrix([[2, 3, -1, 4], [-1, 4, 1, 4], [1, 7, 0, 8]])
A_rref = A.rref()
display(A_rref)

(Matrix([
 [1, 0, -7/11,  4/11],
 [0, 1,  1/11, 12/11],
 [0, 0,     0,     0]]),
 (0, 1))

Для более красивого вывода на экран "распакуем" результат, возвращаемый rref, с помощью *

In [24]:
display(*A_rref)

Matrix([
[1, 0, -7/11,  4/11],
[0, 1,  1/11, 12/11],
[0, 0,     0,     0]])

(0, 1)

Каждый элемент кортежа, возвращаемого rref стал отдельным аргументом функции display и был отрисован.

rref возвращает кортеж, первый элемент которого - ступенчатый вид матрицы, второй - кортеж из номеров ведущих столбцов матрицы.

Для получения матрицы полного столбцового ранга выделим из матрицы $A$ ведущие столбцы (в соответствии с кортежем номеров столбцов, полученным благодаря rref).



In [25]:
cols = A_rref[1]
k = len(cols)
B = A[:, cols]
print(f'cols = {cols}, k = {k}, B = {B}')
display(B)

cols = (0, 1), k = 2, B = Matrix([[2, 3], [-1, 4], [1, 7]])


Matrix([
[ 2, 3],
[-1, 4],
[ 1, 7]])

Для выделения нужных столбцов из матрицы воспользуемся срезом:
```
B = A[:, cols]
```
В квадратных скобках указываем номера нужных строк (все строки обозначаются :) и номера столбцов. Номера могут быть диапазонами (например, 2:6),кортежами (например, (3, 6, 8)), списками, а еще можно использовать range.

Выделим из $A_{rref}$ ненулевые строки, получим матрицу $C$ полного строчного ранга.


In [26]:
C = A_rref[0][:k, :]
print('C =')
display(C)

C =


Matrix([
[1, 0, -7/11,  4/11],
[0, 1,  1/11, 12/11]])

Составим по формуле
$$
A^+ = C^T(C\cdot C^T)^{-1}(B^T\cdot B)^{-1}B^T
$$
псевдообратную матрицу

In [27]:
A_pinv_my = C.T * (C * C.T) ** (-1) * (B.T * B) ** (-1) * B.T
A_pinv = A.pinv()
display('A =', A, 'B', B, 'C', C, 'A_pinv', A_pinv, 'A_pinv_my', A_pinv_my)
print(f'Равенство A.pinv() == A_pinv_my {"не " * (not (A_pinv == A_pinv_my))}\
выполняется')

'A ='

Matrix([
[ 2, 3, -1, 4],
[-1, 4,  1, 4],
[ 1, 7,  0, 8]])

'B'

Matrix([
[ 2, 3],
[-1, 4],
[ 1, 7]])

'C'

Matrix([
[1, 0, -7/11,  4/11],
[0, 1,  1/11, 12/11]])

'A_pinv'

Matrix([
[ 266/1185, -253/1185, 13/1185],
[ -41/1185,   88/1185, 47/1185],
[-173/1185,  169/1185, -4/1185],
[  52/1185,    4/1185, 56/1185]])

'A_pinv_my'

Matrix([
[ 266/1185, -253/1185, 13/1185],
[ -41/1185,   88/1185, 47/1185],
[-173/1185,  169/1185, -4/1185],
[  52/1185,    4/1185, 56/1185]])

Равенство A.pinv() == A_pinv_my выполняется


## Функции для работы с array.
https://numpy.org/doc/stable/reference/routines.array-manipulation.html
### Копирование
При копировании с помощью присваивания получается новый указатель на тот же объект, а не физически независимая копия. Но при использовании операции умножения на число результат другой, сравните:

In [28]:
ar1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
ar2 = 2 * ar1
print(ar1, ar2, sep='\n\n', end='\n\n---\n\n')
ar1[0, 0] = -1
ar2[1, 1] = 100
print(ar1, ar2, sep='\n\n')

[[1 2 3 4]
 [5 6 7 8]]

[[ 2  4  6  8]
 [10 12 14 16]]

---

[[-1  2  3  4]
 [ 5  6  7  8]]

[[  2   4   6   8]
 [ 10 100  14  16]]


ar1 и ar2 изменяются независимо

Теперь не будем умножать:

In [29]:
ar1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
ar2 = ar1
print(ar1, ar2, sep='\n\n', end='\n\n---\n\n')
ar1[0, 0] = -1
ar2[1, 1] = 100
print(ar1, ar2, sep='\n\n')

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]]

---

[[ -1   2   3   4]
 [  5 100   7   8]]

[[ -1   2   3   4]
 [  5 100   7   8]]


Видно, что ar2 - это новый указатель на ar1.

Умножим на 1:

In [30]:
ar1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
ar2 = 1 * ar1
print(ar1, ar2, sep='\n\n', end='\n\n---\n\n')
ar1[0, 0] = -1
ar2[1, 1] = 100
print(ar1, ar2, sep='\n\n')

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]]

---

[[-1  2  3  4]
 [ 5  6  7  8]]

[[  1   2   3   4]
 [  5 100   7   8]]


Этот способ очень не рекомендуется применять в групповом или развивающемся проекте,
поскольку велики шансы, что кто-нибудь решит убрать "ненужную" единицу и все сломается.

Попробуйте все то же самое проделать с списком list. Тут умножение не помогает:

In [31]:
list1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
list2 = 1 * list1
print(list1, list2, sep='\n\n', end='\n\n---\n\n')
list1[0][0] = -1
list2[1][1] = 100
print(list1, list2, sep='\n\n', end='\n\n---\n\n')

[[1, 2, 3, 4], [5, 6, 7, 8]]

[[1, 2, 3, 4], [5, 6, 7, 8]]

---

[[-1, 2, 3, 4], [5, 100, 7, 8]]

[[-1, 2, 3, 4], [5, 100, 7, 8]]

---



### Копирование с numpy.copyto
numpy.copyto(dst, src, casting='same_kind', where=True)

dst - куда (копировать)

src - что (копировать)

Скопируем ar1 в ar2

In [32]:
ar1 = np.array([[-1, 2, -3, 4], [5, -6, 7, -8]])
np.copyto(ar2, ar1)
print(ar1, ar2, sep='\n\n', end='\n\n---\n\n')
ar1[0, 0] = 555
ar2[1, 1] = 777
print(ar1, ar2, sep='\n\n')

[[-1  2 -3  4]
 [ 5 -6  7 -8]]

[[-1  2 -3  4]
 [ 5 -6  7 -8]]

---

[[555   2  -3   4]
 [  5  -6   7  -8]]

[[ -1   2  -3   4]
 [  5 777   7  -8]]


### numpy.asarray(a, dtype=None, order=None) 
возвращает array, полученный на основе аргумента a.

In [33]:
a = [1, 2, 3]
b = np.asarray(a)
print(a, b, sep='\n\n')

[1, 2, 3]

[1 2 3]


### numpy.concatenate((a1, a2, ...), axis=0, out=None)
соединяет аргументы в один array

In [34]:
print(np.concatenate((ar1[:, :-1], [a])))

[[555   2  -3]
 [  5  -6   7]
 [  1   2   3]]


### numpy.stack(arrays, axis=0, out=None)
соединяет аргументы в один array, все аргументы должны быть одинаковых размерностей:

In [35]:
ar3 = np.array([6, 7, 8])
ar4 = np.array([16, 0, -8])
print(np.stack((ar3, ar4)))

[[ 6  7  8]
 [16  0 -8]]


### numpy.vstack(tup)

In [36]:
ar3 = np.array([[6, 3], [7, 4], [8, 5]])
ar4 = np.array([[1, 16], [2, 0], [3, -8]])
print(np.vstack((ar3, ar4)))

[[ 6  3]
 [ 7  4]
 [ 8  5]
 [ 1 16]
 [ 2  0]
 [ 3 -8]]


Сравните с numpy.stack

In [37]:
print(np.stack((ar3, ar4)))

[[[ 6  3]
  [ 7  4]
  [ 8  5]]

 [[ 1 16]
  [ 2  0]
  [ 3 -8]]]


### numpy.hstack(tup)

In [38]:
print(np.hstack((ar3, ar4)))

[[ 6  3  1 16]
 [ 7  4  2  0]
 [ 8  5  3 -8]]


# Дополнительные возможности для информативного вывода результатов вычислений на экран

Подключим функцию latex из библиотеки sympy для получения представлнения математического выражения на Python в виде текста формулы в Латех. Также понадобится Matrix - конструктор матриц из sympy.

In [39]:
from sympy import latex, Matrix

Составим формулу для матрицы $A$ из предыдущего примера.

In [40]:
print(latex(Matrix(A)))

\left[\begin{matrix}2 & 3 & -1 & 4\\-1 & 4 & 1 & 4\\1 & 7 & 0 & 8\end{matrix}\right]


Для того, чтобы такие формулы выводились на экран в виде изображения формулы, нужно подключить функцию Latex из библиотеки IPython.display

In [41]:
from IPython.display import Latex

Выведем на экран изображение матрицы $A$:

In [42]:
display(Latex(latex(Matrix(A))))

<IPython.core.display.Latex object>

Можно в одной строке разместить текст и формулы:

In [43]:
display(Latex(f'Матрица\ A:\ {latex(Matrix(A))}'))

<IPython.core.display.Latex object>

В математическом режиме игнорируются пробелы, поэтому их пришлось экранировать с помощью \

Альтернатива - использовать \text{} (средство Latex) 

In [44]:
display(Latex(f'\\text{{Матрица A: }}{latex(Matrix(A))}'))

<IPython.core.display.Latex object>

В f-строке для группировки понадобились фигурные скобки, их пришлось удвоить, кроме того, понадобилось экранировать \ перед text, поэтому написали \\text{{Матрица A: }}.