# **Лабораторная работа 2**
# **Прикладная алгебра и численные методы**
## Число обусловленности, итерационные методы решения СЛАУ, теорема Фробениуса-Перрона, PageRank, собственные значения, характеристический многочлен.

In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import scipy.linalg
import sympy
from sympy import Matrix, simplify, expand
from IPython.display import Latex, Math

## Задание 1.
Считать данные из файла "Problem1lab2vxx.xlsx", на листе "A1" матрица левой части СЛАУ $AX = b$, на листе "b1" - вектор правой части СЛАУ.

Вычислить матричные нормы $||A_1||_1$, $||A_1||_2$, $||A_1||_\infty$, $||A_1||_{nuc}$ и $||A_1||_F$  для матрицы $A_1$ и соответствующие подчиненные векторные нормы для вектора $b$. Вывести на экран на отдельных строках матричные и векторные нормы, в каждой строке одна матричная норма и соответствующая векторная.

In [58]:
A = pd.read_excel("Problem1lab2v15.xlsx").to_numpy()
deltaA = pd.read_excel("Problem1lab2v15.xlsx", sheet_name='deltaA3').to_numpy()
deltab = pd.read_excel("Problem1lab2v15.xlsx", sheet_name='deltab3').to_numpy()
b = pd.read_excel("Problem1lab2v15.xlsx", sheet_name='b3').to_numpy()

norm_1 = np.linalg.norm(A, ord=1)
norm_2 = np.linalg.norm(A, ord=2)
norm_inf = np.linalg.norm(A, ord=np.inf)
norm_nuc = np.linalg.norm(A, ord='nuc') 
norm_fro = np.linalg.norm(A, ord='fro')

norm_1_vec = np.linalg.norm(b, ord=1)
norm_2_vec = np.linalg.norm(b, ord=2)
norm_inf_vec = np.linalg.norm(b, ord=np.inf)

print("Матричные нормы:")
print("||A1||_1 =", norm_1)
print("||A1||_2 =", norm_2)
print("||A1||_inf =", norm_inf)
print("||A1||_nuc =", norm_nuc)
print("||A1||_F =", norm_fro)

print("Векторные нормы:")
print("||b||_1 =", norm_1_vec)
print("||b||_2 =", norm_2_vec)
print("||b||_inf =", norm_inf_vec)


Матричные нормы:
||A1||_1 = 139.0
||A1||_2 = 50.15638021442877
||A1||_inf = 145.0
||A1||_nuc = 543.4091146809428
||A1||_F = 133.08268106707197
Векторные нормы:
||b||_1 = 3018.0
||b||_2 = 816.3099901385501
||b||_inf = 369.0


## Задание 2. Число обусловленности. Погрешность решения СЛАУ. 

Найти число обусловленности матрицы $A_1$ Задания 1 в нормах 1, 2, inf. 
Вывести на экран найденные значения числа обусловленности.

К матрице  $A_1$ прибавить матрицу искажений с листа  "deltaA" файла "Problem1lab2vxx.xlsx",
к $b_1$ Задания 1  прибавить столбец искажений с листа  "deltab" файла "Problem1lab2vxx.xlsx". 

Найти решения исходной и искаженной СЛАУ с помощью np.linalg.solve, вычислить норму (1, 2, inf) их разности, вывести на экран решения и нормы их разности.

In [59]:
_, singular_values, _ = np.linalg.svd(A)
cond_1 = np.linalg.norm(singular_values, ord=1) * np.linalg.norm(np.linalg.pinv(A), ord=1)
cond_2 = np.linalg.norm(singular_values, ord=2) * np.linalg.norm(np.linalg.pinv(A), ord=2)
cond_inf = np.linalg.norm(singular_values, ord=np.inf) * np.linalg.norm(np.linalg.pinv(A), ord=np.inf)

A1_delta = A + deltaA
b1_delta = b + deltab

x, _, _, _ = np.linalg.lstsq(A, b, rcond=None)
x1_delta, _, _, _ = np.linalg.lstsq(A1_delta, b1_delta, rcond=None)

norm_diff_1 = np.linalg.norm(x - x1_delta, ord=1)
norm_diff_2 = np.linalg.norm(x - x1_delta, ord=2)
norm_diff_inf = np.linalg.norm(x - x1_delta, ord=np.inf)

print("Число обусловленности:")
print("cond_1 =", cond_1)
print("cond_2 =", cond_2)
print("cond_inf =", cond_inf)

print("\nРешение исходной СЛАУ:")
print(x)

print("\nРешение искаженной СЛАУ:")
print(x1_delta)

print("\nНормы разности решений:")
print("||x1 - x1_delta||_1 =", norm_diff_1)
print("||x1 - x1_delta||_2 =", norm_diff_2)
print("||x1 - x1_delta||_inf =", norm_diff_inf)


Число обусловленности:
cond_1 = 954.8747971909315
cond_2 = 148.83266942342536
cond_inf = 126.34020305701546

Решение исходной СЛАУ:
[[ 2.04476746]
 [ 1.57839   ]
 [ 3.06285554]
 [ 2.27251483]
 [-8.24314489]
 [-4.65121348]
 [ 1.26359458]
 [-8.17444777]
 [-8.64049837]
 [-9.59436576]
 [ 1.73844958]
 [ 5.91016577]
 [-9.11605811]
 [-1.98363715]
 [ 7.92802486]
 [ 6.23986864]
 [ 1.95589682]
 [-3.07418706]
 [ 6.15827292]
 [ 7.74827964]
 [ 3.62850142]
 [ 3.02346895]
 [-3.28759089]
 [ 0.68561842]]

Решение искаженной СЛАУ:
[[ 2.04924451]
 [ 1.58094047]
 [ 3.06548531]
 [ 2.27281198]
 [-8.2412327 ]
 [-4.65112227]
 [ 1.26009734]
 [-8.17509178]
 [-8.64108182]
 [-9.59058146]
 [ 1.73674434]
 [ 5.90859974]
 [-9.11586017]
 [-1.98481184]
 [ 7.93373595]
 [ 6.23502516]
 [ 1.95723867]
 [-3.07296513]
 [ 6.15843173]
 [ 7.74471789]
 [ 3.63101644]
 [ 3.02420626]
 [-3.28500584]
 [ 0.68479014]]

Нормы разности решений:
||x1 - x1_delta||_1 = 0.04861530857318397
||x1 - x1_delta||_2 = 0.012554764335426998
||x1 - x1_

## Задание 3 Погрешность решения СЛАУ. 
Проверить, что для СЛАУ Задания 1 выполняется неравенство:
$$
(1)\qquad\frac{\delta b}{\chi(A)}  \le \delta 
X \le \chi(A)\delta b,
$$
где  $\chi(A)$ число обусловленности,
$\delta X = \frac{||\Delta X||}{||X||}$, $\delta b = \frac{||\Delta b||}{||b||}$, $\Delta X = X - X^*$ - разность точного решения $X$ СЛАУ $A_1X = b$ и $X^*$ - решения искаженной СЛАУ $A_1X = b^*$, $b^* = b + \Delta b$,
$\Delta b$ - столбец искажений с листа deltab.

Внимание!!! $X^*$ не из Задания 1, $X^*$ - решение СЛАУ с неискаженной матрицей левой части $A_1$!

Норма 2-norm, (т.е. для матрицы спектральная, для вектора - Евклидова).

Вывести на экран значения  $\delta X$, $\delta b$, $\frac{\delta b}{\chi(A)}$, $\chi(A)\delta b$ и результат проверки выполнения неравенств (текст "Верно" или "Неверно", он должен быть получен автоматически на основе вычислений).

Показать, что для $X^*$ из Задания 1 неравенства (1) НЕ выполняются.

Показать, что для $X^*$ из Задания 1 выполняется неравенство:
$$
(2)\qquad\frac{\delta b + \delta A}{\chi(A)}  \le \delta 
X \le \chi(A)(\delta b  + \delta A).
$$

In [60]:
delta_X = np.linalg.norm(x - x1_delta) / np.linalg.norm(x)
delta_b = np.linalg.norm(deltab) / np.linalg.norm(b)
left_side = delta_b / cond_2
right_side = cond_2 * delta_b

print("delta_X =", delta_X)
print("delta_b / cond_2 =", left_side)
print("cond_2 * delta_b =", right_side)

print("Неравенство 1:", "Верно" if (left_side <= delta_X <= right_side) else "Неверно")



delta_A = np.linalg.norm(deltaA) / np.linalg.norm(A)
left_side = (delta_b + delta_A) / cond_2
right_side = cond_2 * (delta_b + delta_A)

print("неравенство 2:", "Верно" if (left_side <= delta_X <= right_side) else "Неверно")


delta_X = 0.0004686928989414159
delta_b / cond_2 = 1.928444003315773e-08
cond_2 * delta_b = 0.0004271727839432741
Неравенство 1: Неверно
неравенство 2: Верно


## Задание 4 Погрешность обратной матрицы. 
Для матрицы $A_1$ Задания 1 оценить сверху погрешность приближения обратной матрицы $\hat A = A_1 + \Delta A_1$ при условии, что $\Delta A_1$ -  матрица  искажений с листа  "deltaA" файла "Problem1lab2vxx.xlsx". 
Для оценки использовать неравенство 
$$
(3)\qquad \delta  A_1^{-1} \le \frac{\chi(A_1)\delta A_1}{1 - \chi(A_1)\delta A_1}, \quad 
  \delta  A_1^{-1} = \frac{||{\hat A_1}^{-1} - A_1^{-1}||}{||A_1^{-1}||},\quad 
 \delta A_1 = \frac{||\Delta A_1||}{||A_1||}.
$$

Найти обратные матрицы для $A_1$ и $\hat A_1$. Сравнить $\delta  A_1^{-1} = \frac{||{\hat A_1}^{-1} - A_1^{-1}||}{||A_1^{-1}||}$ и правую часть неравенства, проверить выполнение неравенства.

Вывести на экран значение левой и правой частей неравенства  и результат проверки выполнения неравенств (текст "Верно" или "Неверно", он должен быть получен автоматически на основе вычислений).

In [61]:
delta_A = np.linalg.norm(deltaA) / np.linalg.norm(A)
A_pinv = np.linalg.pinv(A)
A_h = A + deltaA
A_h_pinv = np.linalg.pinv(A_h)
delta_A1_inv = np.linalg.norm(A_h_pinv - A_pinv) / np.linalg.norm(A_pinv)

right_side = (cond_2 * delta_A) / (1 - cond_2 * delta_A)
is_valid = delta_A1_inv <= right_side

print("Левая часть:", delta_A1_inv)
print("Правая часть:", right_side)
print("Выполнение неравенства:", "Верно" if is_valid else "Неверно")


Левая часть: 0.002658973317580886
Правая часть: 0.015074319022901945
Выполнение неравенства: Верно


## Задание 5 Итерационные методы решения СЛАУ.
Написать функцию, решающую СЛАУ методом верхней релаксации (с выбором оптимального значения $\tau$). По умолчанию точность 0.01. 
Решить с помощью этой функции СЛАУ из файла Problem5lab2vxx.xlsx (на листе matrix матрица левой части, на листе b - вектор правой части).

In [62]:
def solve(A, b, tul=0.01, max_iterations=10000):
    n = len(b); x = np.zeros(n); x_prev = np.zeros(n); k = 0; omega = 1
    res = np.inf
    while (res > tul) and (k < max_iterations):
        x_prev = np.copy(x)
        for i in range(n):
            sigma = 0
            for j in range(n):
                if j != i:
                    sigma += A[i][j] * x[j]
            x[i] = (1 - omega) * x_prev[i] + (omega / A[i][i]) * (b[i] - sigma)
        res = np.linalg.norm(x@A - b)
        temp = 1 - (res / tul) ** (1 / (k + 1))
        if temp < 0:
            omega = 0
        else:
            omega = 2 / (1 + np.sqrt(temp))
        k += 1    
    return x

A = pd.read_excel("Problem5lab2v15.xlsx", sheet_name="A5").to_numpy()
b = pd.read_excel("Problem5lab2v15.xlsx", sheet_name="b5").to_numpy()

solution = solve(A, b)

print(solution)

[  174.           -28.0625        -2.75520833  -173.20543981
   199.88015572  -348.45261644   565.93227998  -907.40915187
   247.66664309   737.06571724   514.53434761 -2307.77693816
  1672.43972558  -744.38122523   637.24927738   804.44625069
   247.02748988  -464.24114644 -1108.17296638  -290.88847957]


## Задание 6 Теорема Фробениуса-Перрона.

Для графа из файла Problem6lab2vxx.jpg построить и вывести на экран матрицу смежности. Найти и вывести на экран модули всех собственных значений матрицы смежности, максимальное по модулю собственное значение матрицы смежности и соответствующий (положительный!) единичный собственный вектор (норма 2).

Проверить, что модули остальных собственных значений меньше.

In [63]:
A = np.array([[0, 3, np.inf, 2, 8, 3],
              [3, 0, 6, np.inf, np.inf, np.inf],
              [np.inf, 6, 0, 4, np.inf, 9],
              [2, np.inf, 4, 0, 5, np.inf],
              [8, np.inf, np.inf, 5, 0, 3],
              [3, np.inf, 9, np.inf, 3, 0]])
A[np.isinf(A)] = 1e10
eigs, eigenvectors = np.linalg.eig(A)
abs_eigs = np.abs(eigs)

print("Модули собственных значений:")
for value in abs_eigs:
    print(value)

max_abs_eig = np.max(abs_eigs)
print("\nМаксимальное по модулю собственное значение:", np.max(abs_eigs))

max_eig_ind = np.argmax(abs_eigs)
max_eigenvector = eigenvectors[:, max_eig_ind]
positive_eigenvector = max_eigenvector / np.linalg.norm(max_eigenvector, 2)

print("\nЕдиничный собственный вектор:")
print(positive_eigenvector)

other_eigs = np.delete(abs_eigs, max_eig_ind)
print("\nПроверка:", np.all(other_eigs < max_abs_eig))



Модули собственных значений:
22283282167.47199
13604093365.630463
1858853456.7813709
17746228990.455246
9999999998.175665
10000000001.252903

Максимальное по модулю собственное значение: 22283282167.47199

Единичный собственный вектор:
[0.09008014 0.59524854 0.20072813 0.48460056 0.357208   0.48460056]

Проверка: True


## Задание 7.
Найти самую влиятельную вершину в графе, заданном матрицей смежности из файла Problem7lab2vxx.xlsx

In [64]:
A = pd.read_excel('Problem7lab2v15.xlsx').to_numpy()

column_sums = np.sum(A, axis=0)
most_influential_vertex = np.argmax(column_sums)

print(most_influential_vertex)


3


## Задание 8
Описать функцию, которой в качестве обязательного аргумента передается двумерный np.array $A$ с числами  и число $t$ от 0 до 1. Функция возвращает кортеж ($k$, $\delta$, $A_k$), где  $k$ - ранг $A_k$, $\delta= ||A - A_k||_2$, $A_k$ - приближение $A$ ранга $k$. Ранг $k$ функция подбирает из условия $\delta \le t||A||_2$.

Вызвать функцию с матрицами Заданий 1, 5, 6 и 7 при $t=0.25$, вывести на экран на отдельных строках  ранг $A_k$ и $\delta$.

In [65]:

def rank_approximation(A, t):
    U, S, V_ = np.linalg.svd(A);norm_A = np.linalg.norm(A, 2);k = 0
    delta = np.inf; A_k = None
    for i in range(len(S)):
        current_delta = np.linalg.norm(S[i:])
        if current_delta <= t * norm_A:
            k = len(S[i:])
            delta = current_delta
            A_k = np.dot(U[:, :k] * S[:k], V_[:k, :])
            break

    return k, delta, A_k

t = 0.25
A1 = pd.read_excel("Problem1lab2v15.xlsx").to_numpy()
A5 = pd.read_excel("Problem5lab2v15.xlsx", sheet_name="A5").to_numpy()
A6 = np.array([[0, 3, np.inf, 2, 8, 3],
              [3, 0, 6, np.inf, np.inf, np.inf],
              [np.inf, 6, 0, 4, np.inf, 9],
              [2, np.inf, 4, 0, 5, np.inf],
              [8, np.inf, np.inf, 5, 0, 3],
              [3, np.inf, 9, np.inf, 3, 0]])
A6[np.isinf(A6)] = 1e10
A7 = pd.read_excel('Problem7lab2v15.xlsx').to_numpy()

for i, A in enumerate([A1, A5, A6, A7], start=1):
    k, delta, A_k = rank_approximation(A, t)
    print("Ранг A{i}:", k)
    print("Дельта:", delta)

Ранг A{i}: 5
Дельта: 11.701859461456035
Ранг A{i}: 0
Дельта: inf
Ранг A{i}: 1
Дельта: 1858853456.7813716
Ранг A{i}: 1
Дельта: 0.15140555532261923


### Задание  9.
Построить  QR разложение и жорданову форму для матрицы из файла "Problem9lab2vxx.xlsx",
показать, что $A = QR$.