# Занятие 1
# Прикладная алгебра и численные методы
## Матрицы и системы линейных алгебраических уравнений (СЛАУ)
numpy:
https://numpy.org/doc/stable/reference/routines.linalg.html

In [14]:
import numpy as np
import sympy as sp
import scipy.linalg

#### Задание 1
$$
\left\{
\begin{matrix}
2x + 3y - z = 5\\
3x - 2y + z = 2\\
5x + y = 0
\end{matrix}
\right.
$$
Составить матрицу левой части и вектор правой частив виде array. Из полученных матриц составить расширенную матрицу СЛАУ (не перенабирать числа вручную!). Вывести все матрицы на экран.

In [15]:
L = np.array([[2, 3, -1], 
              [3, -2, 1], 
              [5, 1, 0]])

psi = np.array([2, 5, 0]).reshape((3,1))
G = np.hstack((L, psi))
print('G', G, sep='=')

G=[[ 2  3 -1  2]
 [ 3 -2  1  5]
 [ 5  1  0  0]]


#### Задание 2
Составить матрицу $A_{4\times5}$ (array), состоящую из чисел от 0 до 19.

Транспонировать матрицу $A$.

Присоединить к этой матрице ***снизу*** ее копию, у которой элементы удвоены.

К исходной матрице $A$ присоединить справа ее первый и последний столбцы (номер последнего элемента в Python это $-1$).

Вывести все матрицы на экран.

Указание: использовать np.arange, reshape, .T, np.vstack, np.hstack

Номера столбцов, которые нужно присоединить, передавать np.hstack в виде кортежа.

In [16]:
A = np.arange(0, 20).reshape((4,5))
print('A', A, sep='=')
A = A.T
print('A', A, sep='=')
A = np.vstack((A, A*2))
print('A', A, sep='=')
f = A[: , 0]
l = A[: , -1]
A = np.hstack((A, f.reshape((f.size,1)), l.reshape((l.size,1))))
print('A', A, sep='=')

A=[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
A=[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
A=[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 0 10 20 30]
 [ 2 12 22 32]
 [ 4 14 24 34]
 [ 6 16 26 36]
 [ 8 18 28 38]]
A=[[ 0  5 10 15  0 15]
 [ 1  6 11 16  1 16]
 [ 2  7 12 17  2 17]
 [ 3  8 13 18  3 18]
 [ 4  9 14 19  4 19]
 [ 0 10 20 30  0 30]
 [ 2 12 22 32  2 32]
 [ 4 14 24 34  4 34]
 [ 6 16 26 36  6 36]
 [ 8 18 28 38  8 38]]


#### Задание 3
Описать функцию print_col, выводящую на экран $n$-й столбец матрицы $A$, номер $n$ по умолчанию равен 0. Аргументы функции матрица $A$ (обязательный) и число $n$ (необязательный, по умолчанию 0).

С помощью вызова этой функции вывести на экран по очереди все столбцы матрицы $A$ (в цикле for), затем еще раз вывести нулевой столбец отдельным вызовом функции print_col(столбцы будут выводиться в строку, это нормально).

In [17]:
def print_col(A,  n = 0):
    A = np.array(A)
    if 0 <= n and n  <= A[0,  :].size:
        print(A[: , n])
    else:
        print("Mistake")

[print_col(A, i) for i in range(A[0,  :].size)]
print_col(A)

[0 1 2 3 4 0 2 4 6 8]
[ 5  6  7  8  9 10 12 14 16 18]
[10 11 12 13 14 20 22 24 26 28]
[15 16 17 18 19 30 32 34 36 38]
[0 1 2 3 4 0 2 4 6 8]
[15 16 17 18 19 30 32 34 36 38]
[0 1 2 3 4 0 2 4 6 8]


#### Задание 3*
Описать функцию concate, присоединяющую справа к матрице $A$ ее столбец с номером $n$, по умолчанию равным 0, и выводящую на экран матрицу $A$, ее $n$-й столбец и резальтат присоединения этого столбца. Аргументы функции матрица $A$ (обязательный) и число $n$ (необязательный, по умолчанию 0)

С помощью вызова этой функции вывести на экран  матрицу $A$, ее 2-й столбец и результат присоединения этого столбца. Вызвать функцию concate(A).

Указание: чтобы полученный в результате среза столбец матрицы получился не одномерным, а двумерным, указывать не номер столбца, а кортеж или список, состоящий из одного этого номера, например, (1,) или [1]. Обратите внимание на запятую в (1,), она необходима для того, чтобы число в скобках было воспринято как кортеж из одного элемента, после такой запятой не ставится пробел.

In [18]:
def concate(A, n=0):
    if 0 <= n and n  <= A[0,  :].size:
        h = A[: , n].reshape((A[:, 0].size,1))
        print(A, h, np.hstack((A, h)), sep='\n')
        return np.hstack((A, h.reshape((f.size,1))))
    else:
        print("Mistake")

_ = concate(A, 2)


[[ 0  5 10 15  0 15]
 [ 1  6 11 16  1 16]
 [ 2  7 12 17  2 17]
 [ 3  8 13 18  3 18]
 [ 4  9 14 19  4 19]
 [ 0 10 20 30  0 30]
 [ 2 12 22 32  2 32]
 [ 4 14 24 34  4 34]
 [ 6 16 26 36  6 36]
 [ 8 18 28 38  8 38]]
[[10]
 [11]
 [12]
 [13]
 [14]
 [20]
 [22]
 [24]
 [26]
 [28]]
[[ 0  5 10 15  0 15 10]
 [ 1  6 11 16  1 16 11]
 [ 2  7 12 17  2 17 12]
 [ 3  8 13 18  3 18 13]
 [ 4  9 14 19  4 19 14]
 [ 0 10 20 30  0 30 20]
 [ 2 12 22 32  2 32 22]
 [ 4 14 24 34  4 34 24]
 [ 6 16 26 36  6 36 26]
 [ 8 18 28 38  8 38 28]]


#### Задание 4
Описать функцию, аргументы которой - матрица $A$  и заранее неизвестное число номеров строк этой матрицы. Функция возвращает матрицу, полученную присоединением снизу к матрице  $A$ строк с переданными в качестве аргументов номерами.

Если в вызове функции есть только матрица, то она же и возвращается.

Вывести на экран результат вызова функции 

с одной только матрицей $A$ Задания 1, 

с матрицей и номером столбца 2, 

с матрицей и номерами столбцов 1 и 3. 

**Указание:** строки выделять из матрицы срезом, передавая номера строк в виде кортежа, возможно, из одного элемента, например, (1,) или [1]. Обратите внимание на запятую в (1,), она необходима для того, чтобы число в скобках было воспринято как кортеж из одного элемента, после такой запятой не ставится пробел.

In [19]:
def n_concate(A, *args):
    ns = args
    for n in ns:
        if 0 <= n and n  <= A[1,  :].size:
            l = A[n , :]
            A = np.vstack((A, l))
        else:
            print("Mistake")
            return None
    return A
print("a) ",  n_concate(L))
print("b) ",  n_concate(L, 1))
print("b) ",  n_concate(L, 0, 2))


a)  [[ 2  3 -1]
 [ 3 -2  1]
 [ 5  1  0]]
b)  [[ 2  3 -1]
 [ 3 -2  1]
 [ 5  1  0]
 [ 3 -2  1]]
b)  [[ 2  3 -1]
 [ 3 -2  1]
 [ 5  1  0]
 [ 2  3 -1]
 [ 5  1  0]]


#### Задание 5
Решить СЛАУ
$$
\left\{
\begin{matrix}
-2.1x + 3y + 4.5z = 10.23\\
3x + 5y + 1.5z = 20.65\\
7.2x + z = 9.34
\end{matrix}
\right.
$$
Для решения СЛАУ воспользоваться linalg.solve, аргументы - матрица левой части и столбец правой.

Для проверки правильности решения использовать allclose.

In [20]:
L = np.array([[-2.1, 3, 4.5], 
             [3, 5, 1.5], 
             [7.2, 0, 1]])
psi = np.array([10.23, 20.65, 9.34]).reshape((3,1))
x = np.linalg.solve(L, psi)
print("x =", x)
print(np.allclose(L @ x, psi))

x = [[1.2]
 [3.2]
 [0.7]]
True


#### Задание 6
$$
A = \left(
\begin{matrix}
1 & 2 & -5 & 9 & 1\\
3 & 1 & 2 & -5 & 0
\end{matrix}
\right)
$$
Найти псевдообратную матрицу к матрице A средствами numpy, scipy и sympy.

In [21]:
A = np.array([[1, 2, -5, 9, 1],
              [3, 1, 2, -5, 0]])
print("numpy:\n",np.linalg.pinv(A))
print("scipy:\n",scipy.linalg.pinv(A), "\nsympy:")
As = sp.Matrix(A)
As_pinv = As.pinv()
display(As_pinv, As_pinv.evalf(8))

numpy:
 [[ 0.10117773  0.20663812]
 [ 0.06852248  0.11349036]
 [-0.05085653 -0.01391863]
 [ 0.05406852 -0.05888651]
 [ 0.02087794  0.0267666 ]]
scipy:
 [[ 0.10117773  0.20663812]
 [ 0.06852248  0.11349036]
 [-0.05085653 -0.01391863]
 [ 0.05406852 -0.05888651]
 [ 0.02087794  0.0267666 ]] 
sympy:


Matrix([
[189/1868, 193/934],
[  32/467,  53/467],
[-95/1868, -13/934],
[101/1868, -55/934],
[ 39/1868,  25/934]])

Matrix([
[  0.10117773,  0.20663812],
[ 0.068522484,  0.11349036],
[-0.050856531, -0.01391863],
[ 0.054068522, -0.05888651],
[ 0.020877944, 0.026766595]])

#### Задание 7
Построить скелетное разложение для матрицы 
$
\left(
\begin{matrix}
1 & 2 & -5 & 9 & 1\\
4 & 3 & -3 & 4 & 1\\
5 & 5 & -8 & 13 & 2\\
3 & 1 & 2 & -5 & 0
\end{matrix}
\right)
$

**Скелетное разложение**
$$
A^+ = C^T(C\cdot C^T)^{-1}(B^T\cdot B)^{-1}B^T,
$$
где $B$ матрица полного столбцового ранга, $C$-строчного.

На основе полученного разложения составить псевдообратную матрицу, затем вывести на экран полученную псевдообратную матрицу, ее представление в виде вещественных чисел (evalf()) и результат применения pinv из numpy к матрице, заданной в виде np.array.

#### Задание 8
Описать функцию, которая находит  скелетное разложение для матрицы  $A$

**Скелетное разложение**
$$
A^+ = C^T(C\cdot C^T)^{-1}(B^T\cdot B)^{-1}B^T,
$$
где $B$ матрица полного столбцового ранга, $C$-строчного.

Функция возвращает кортеж из матриц $B$, $C$  и $A^+$, найденной по формуле выше.


#### Задание 9*
Описать функцию, которая возвращает матрицу, состоящую из $n$ блоков 
$
\left(
\begin{matrix}
1 & 2\\
4 & 3
\end{matrix}
\right)
$
на главной диагонали и $k$ правых столбцов из единиц, остальные элементы нули. Пример такой матрицы:
$
\left(
\begin{matrix}
1 & 2 & 0 & 0 & 1\\
4 & 3 & 0 & 0 & 1\\
0 & 0 & 1 & 2 & 1\\
0 & 0 & 4 & 3 & 1\\
\end{matrix}
\right)
$